# Generated by Django 3.0 on 2019-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('types', models.CharField(max_length=30)),
                ('link_img', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('link_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
