# Generated by Django 3.0 on 2019-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20191211_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pokemons', models.ManyToManyField(to='MyApp.Pokemon')),
            ],
        ),
    ]
