# Generated by Django 3.0 on 2019-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemons',
            field=models.ManyToManyField(null=True, to='MyApp.Pokemon'),
        ),
    ]
